vich_uploader:
    db_driver: orm

    mappings:
        product_images_formula:
            uri_prefix: /images/products/formulas
            upload_destination: '%kernel.project_dir%/public/images/products/formulas'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        product_images_pictogram:
            uri_prefix: /images/products/pictograms
            upload_destination: '%kernel.project_dir%/public/images/products/pictograms'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        product_security_form:
            uri_prefix: /images/products/securityForms
            upload_destination: '%kernel.project_dir%/public/images/products/securityForms'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
